### PR TITLE
Initial changes for Nexus

### PR DESCRIPTION
**Pull request by emveepee**
Initial support for removal of old versions.  Incorporate two changes from Matrix PR #190

### CODE REVIEW

**Comment by emveepee** [comment]
@phunkyfish and @sub3 any concerns?  I'd like to get this out soon since I'd like to ensure the block of backend version users is public ASAP.  I also want to start a bigger PR to remove all the other redundant test conditions based on various old versions and remove unnecessary settings.

The two changes from PR#90 have been user tested in a Matrix test build.

**Comment by phunkyfish** [comment]
Ah, you never requested a review 😉

**Review by phunkyfish — APPROVED** [review]

**Comment by phunkyfish** [comment]
But just needs addon.xml etc.

**Comment by emveepee** [comment]
> 
> 
> Ah, you never requested a review 😉

Sorry you are always so fast I didn't think to do that.   Do I need to add this? I forgot to ask which is why I didn't update the changelog etc.

```
capabilities.SetSupportsProviders(false);
```

**Comment by phunkyfish** [comment]
> > Ah, you never requested a review 😉
> 
> Sorry you are always so fast I didn't think to do that. Do I need to add this? I forgot to ask which is why I didn't update the changelog etc.
> 
> ```
> capabilities.SetSupportsProviders(false);
> ```

That would be the default anyway. You can add it to be explicit if you  like.

**Comment by emveepee** [comment]
> 
> > ```
> > capabilities.SetSupportsProviders(false);
> > ```
> 
> That would be the default anyway. You can add it to be explicit if you like.

Thanks I will add it.  I also decided to remove the unneeded EDL check in the final commit with the release files.

**Review by phunkyfish — APPROVED** [review]

**Pull request merged**
