### PR TITLE
Update PVR API 6.2.0 

### PR DESCRIPTION
**Pull request by emveepee**

### CODE REVIEW

**Comment by emveepee** [comment]
I don't know where the changes on my end are coming how did the build get incremented to 4.3.2?
Edit:  I figured it out, I didn't handle the unexpected merge of my last PR with a rebase
> 
> 
> The transfix guys only increment version number as well as strings.po.
> 
> So just change to 4.3.3 next and add the extra 4.3.2 changelog entry for transifix

**Comment by phunkyfish** [comment]
You mean in addon.xml?

**Comment by emveepee** [comment]
> 
> 
> You mean in addon.xml?

No in artifacts, since I didn't change addon.xml.in  I realize now that translation did that but it didn't know 4.3.1  wasn't released.

**Comment by phunkyfish** [comment]
The transfix guys only increment version number as well as strings.po.

So just change to 4.3.3 next and add the extra 4.3.2 changelog entry for transifix

**Comment by emveepee** [comment]
> 
> 
> The transfix guys only increment version number as well as strings.po.
> 
> So just change to 4.3.3 next and add the extra 4.3.2 changelog entry for transifix

Thanks got it.

**Comment by emveepee** [comment]
@sub3 could you review this and tag as 4.3.3-Matrix for release if acceptable.   I'd like to get this tagged soon since the existing addon will not work with the new API.

**Comment by emveepee** [comment]
@sub3 could you hold off on the tag @phunkyfish  is working on a PR to show other flags then new and we might as well get them all in.

**Comment by phunkyfish** [comment]
I wouldn’t hold off. It could be several days for the new stuff and users on nightlies will have no working addon until the next PR.

**Comment by emveepee** [comment]
> 
> 
> I wouldn’t hold off. It could be several days for the new stuff and users on nightlies will have no working addon until the next PR.

Fair enough.   Thanks for all your work

**Comment by MilhouseVH** [comment]
Build issue with latest kodi master 3a9c94d813f42efc16b4c7ad41c46ab2f82aa5bf :http://ix.io/2ex4

Is this change dependent on https://github.com/xbmc/xbmc/pull/17515 ?

**Comment by MilhouseVH** [comment]
Nope, looks like the upstream change is already merged, https://github.com/xbmc/xbmc/pull/17192 - I guess this PR needs additional work?

**Comment by phunkyfish** [comment]
Do you have the latest nextpvr @MilhouseVH?

**Comment by emveepee** [comment]
I don't think you have the correct version from github  I see 

-- NEXTPVR_VERSION=4.3.2

**Comment by phunkyfish** [comment]
This PR is 4.3.3. Your log is 4.3.0

**Comment by MilhouseVH** [comment]
yeah sorry just noticed when this merged - my build started 10 mins before so was using the old version, my bad (cooking dinner so had little time to investigate!) I'm sure this will be OK once I'm using the correct version!

**Pull request merged**
