### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://kodi.weblate.cloud/projects/kodi-add-ons-pvr-clients/pvr-nextpvr/) for Kodi add-ons: PVR clients/pvr.nextpvr.

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by AlwinEsch** [comment]
@gade01 how is the way in case like here, can be a close enough or must be something triggered outside for it?

EDIT: Mean that weblate does a rebase about.

**Comment by gade01** [comment]
@AlwinEsch This can be merged with no problems as I see it.
Merging will trigger the workflow.

**Review by gade01 — APPROVED** [review]

**Comment by AlwinEsch** [comment]
> @AlwinEsch This can be merged with no problems as I see it.
> Merging will trigger the workflow.

Ah, the 
```
Conflicting files
pvr.nextpvr/resources/language/resource.language.ko_kr/strings.po
```
?

**Comment by gade01** [comment]
Ah, sorry didn't see that.
Yeah, that would cause conficts as Weblate somehow don't have description, summary and disclaimer added.

**Comment by gade01** [comment]
@AlwinEsch Seems I got it all.
Weblate didn't sync everything. So I resat the entire component at Weblate and restored all translations to this PR.

**Comment by AlwinEsch** [comment]
Thanks a lot!

**Pull request merged**
