### PR TITLE
Fixed two errors with message strings

### PR DESCRIPTION
**Pull request by sub3**
- fixed issue with Transifex overwriting strings with older strings
- added extra 'Repeating (keyword)' string to correct duplicate recording type entry

### CODE REVIEW

**Comment by ksooo** [comment]
I think you should open a PR for this for  Jarvis branch as well.

**Comment by sub3** [comment]
Argh - sorry. I this is gonna be more complicated to fix than I hoped. I'll have another go at it in the morning.

**Comment by ksooo** [comment]
In the morning? It's 8:30 am where I live. ;-) Where are you from?

**Comment by sub3** [comment]
New Zealand, but I keep pretty early hours. It's about 5:30 am here, and I'm just getting up.

**Comment by sub3** [comment]
Ok, this should be good now for master. I just have to work out how to get this on the Jarvis branch too.

**Comment by ksooo** [comment]
git cherry-pick is your friend

**Comment by sub3** [comment]
It seems I know just enough about git to be dangerous ;-)

My attempt to use cherry-pick the changes and apply them to a Jarvis branch on my sub3/pvr.nextpvr, appears to have directly updated kodi-pvr/pvr.nextpvr. Do you want to take a look?

**Comment by ksooo** [comment]
Direct push is usually not the way to go. We prefer PRs, because we want to give other devs the chance to review/comment before merge. Anyway, happily nothing bad happened, as your changes were good to go.

Usually a cherry-picking from ypur own repo is pretty simple:
git checkout branch-with-the-commit-to-cherry-pick
git log
(copy the sha of the commit you want to pick)
git checkout Jarvis
git checkout -b jarvis-backport-blah
git cherry-pick sha-picked-before
(resolve conflicts)
git push origin jarvis-backport-blah

**Comment by sub3** [comment]
Yeah, I know. Sorry, it wasn't my intention. I've noted down your instructions there for next time I have to go through the process. 

Thanks!

**Pull request merged**
