### PR TITLE
Rework recording watched state

### PR DESCRIPTION
**Pull request by emveepee**
Maintain play count to manage watched state.  Handle fake return position 0 on resume.  Allow option Kodi for management of resume state.

### CODE REVIEW

**Comment by emveepee** [comment]
@phunkyfish  here are my changes with a stored fake play count.  I added my findings on SetRecordingsLastPlayPostion() and SetRecordingPlayCount() in case others wonder when Kodi send 0 and -1 as the lastplayedposition.  I decided to allow an option to ignore the backend and use the database fields to allow by client settings if desired.

**Review by phunkyfish — APPROVED** [review]
Nice

**Comment by emveepee** [comment]
@phunkyfish  I added another commit to deal with crashing issue with EPG based timer.  I thought there might be a way to resolvr this in Kodi  but @ksooo  advised that my solution wouldn't work and there no other current solution.  These value are not shown to user since they are EPG based but they can't be zero because of negative time_t issues.

**Review by phunkyfish — APPROVED** [review]
Cool, looks fine to me.

**Comment by emveepee** [comment]
@phunkyfish resending this for review of another commit.  Sorry I had stashed this latest commit and forgot about it for a couple of weeks.  I've been using it and thought it was already submitted.

**Review by phunkyfish — APPROVED** [review]

**Pull request merged**
