### PR TITLE
[Matrix] API change update

### PR DESCRIPTION
**Pull request by AlwinEsch**
This changes are related to API change with xbmc/xbmc#17813

Need to bring in after them!

### CODE REVIEW

**Comment by emveepee** [comment]
@AlwinEsch why did you do this at this time?  Although I am grateful for what you do this doesn't help with the port for PR1648 that @phunkyfish  explained I was working on.  Hopefully it will fix a problem I am having with CreateDirectory() with PR1648t though.

**Comment by AlwinEsch** [comment]
There was a part on filesystems parts needed to change (by request for @phunkyfish), where already has needed a update of all addons. For this reason are also few other, not so critical parts added, like the ADDON_LOG_... and the ADDON_Create to cleanup parts.

To split them everything in own requests makes it dramatic to big, if always every addon need update.

Also is this thought to have before PVR API change, as this not critical, but affect all addons. If now together, with the very critical PVR C++ rework becomes to much as also the eyes must on every other addon types then.

What you mean where with **PR1648**? **EDIT:** Do you mean https://github.com/xbmc/xbmc/pull/16485, I think yes :smile: 

**EDIT:** 
Related to PVR is nothing on **old** VFS changed, only need update as it also with his other headers affected to them on `versions.h`.

**Comment by AlwinEsch** [comment]
This request have nothing todo with the PVR rework on Kodi. That's more about `ADDON_GLOBAL_VERSION_MAIN_MIN` where related on `AddonBase.h`, but also to `libXBMC_addon.h` and `xbmc_addon_dll.h` and thats why requests on PVR addons now.

**Comment by phunkyfish** [comment]
@emveepee this change is required to go in prior to the C++ PVR work.

I thought I had mentioned that Alwin would be doing this before the other could be done.

**Comment by phunkyfish** [comment]
Apologies I should have been clearer here: https://github.com/kodi-pvr/pvr.nextpvr/pull/124#issuecomment-628260645

You should be able to rebase after this PR goes in without it being too much work I hope.

**Comment by AlwinEsch** [comment]
I can look to change that the log calls of PVR addons not affected.

**Comment by emveepee** [comment]
It is really my mistake I didn't think the add on was going to be touched and all those ADDON_LOG_ message changes seem rather frivolous and extra work because XBMC->Log is being changed shortly anyway and I have changed them all so I expect this could make a rebase difficult

Edit @AlwinEsch  I just saw your post if you don't change the log message that would certainly be helpful.

**Comment by AlwinEsch** [comment]
Is now a bit smaller :grinning: :smirk:

**Comment by emveepee** [comment]
> 
> 
> Is now a bit smaller 😀 😏

Thanks so much, that is perfect.   I am hoping that when 6.5.1 is released, I will have the addon ready for C++

**Pull request merged**
