### PR TITLE
Style Cleanup

### PR DESCRIPTION
**Pull request by emveepee**
Remove trailing spaces and tabs.

### CODE REVIEW

**Comment by AlwinEsch** [comment]
Always good to have the code cleaner, Thanks!

**Comment by emveepee** [comment]
@mlburgett  I did not include Timeshift.h  It has a few trailing spaces that I could add as an amend if that is ok with you.

**Comment by sub3** [comment]
Thanks for the cleanup!

**Comment by sub3** [comment]
@ksooo hopefully that merge went the way you wanted it? Unfortunately after this merge we did realise there is a 'merge and rebase' option, which I should have used? Sorry - I know just enough to be dangerous 😀

**Pull request merged**
