### PR TITLE
Sync translations

### PR DESCRIPTION
**Pull request by gade01**
This PR will sync translations and translation metadata between matrix and nexus branches.

### CODE REVIEW

**Comment by emveepee** [comment]
@gade01 Can you do a global change on these  In browsing the file I notice that #30504 needs to be changed in the source

from 

msgctxt "#30504"
msgid "Not enabled for Matrix when remote"

to 

msgid "Not enabled when remote"

I would like to take out "for Matrix " in all of them.

**Comment by lrusak** [comment]
@emveepee i think it works that you update the en_gb language and all others are synced from that.

**Comment by emveepee** [comment]
> @emveepee i think it works that you update the en_gb language and all others are synced from that.

I think so too but doesn't the translation automation happen after the merge? I'd like to do this before the merge and tag that we hope to do tomorrow.  

If it can't be removed, can Matrix be changed to Nexus and then I will merge in the removal later.  Serves me right for having a version specific name in there.

**Comment by gade01** [comment]
@emveepee So you'd like to change a string in en_gb as well?
Shouldn't that be done in a seperate PR?

Weblate will always sync all languages based on the source file.

**Comment by emveepee** [comment]
> @emveepee So you'd like to change a string in en_gb as well? Shouldn't that be done in a seperate PR?
> 
I was planning on including it with PR223, but if I need to do another PR to get it done before tomorrow I will.  Does it happen with the merge or tag?

**Comment by gade01** [comment]
I can easily include the change in this PR.

Weblate will sync instantly when changes are merged into en_gb.

**Comment by emveepee** [comment]
OK thanks.  I will ask @sub3 to merge in PR223 and PR230 tonight if he can and we will see what Weblate automation does and tomorrow and maybe can merge it with the tag too.

**Review by emveepee — APPROVED** [review]

**Comment by gade01** [comment]
@emveepee string id 30504 has been changed now in a seperate commit.

**Comment by emveepee** [comment]
> @emveepee string id 30504 has been changed now in a seperate commit.

I already update PR 233 to do this, since I figured the addon was responsible for that file.  It seems I missed Nexus final anyway so it won't make it to ATV

**Comment by emveepee** [comment]
@gade01 ok the merges seems ok now, so will there be another PR generated now or can we tag this?

**Comment by gade01** [comment]
@emveepee You can tag it if you like.
I'll move Weblate to Nexus branch now, which will probably create a new PR.

**Pull request merged**
