### PR TITLE
[Matrix] increase version to 8.0.0 (API related)

### PR DESCRIPTION
**Pull request by AlwinEsch**
API related to xbmc/xbmc#17438 (DEMUX_PACKET not used there)

### CODE REVIEW

**Comment by emveepee** [comment]
Can you update PR 137 to remove this?  I have been holding back on changing the other issues you identified in PR 137 and if you remove it you could update the change log and merge PR 137 right away.

**Comment by AlwinEsch** [comment]
Can swap them over and make for inputstream with here.

**Comment by emveepee** [comment]
@AlwinEsch I assume this needs to be merged now for STREAM_TIME_BASE

**Comment by AlwinEsch** [comment]
There is still the perverse stupid launchpad problem, on which Kodi's build is only triggered one time per day and if addon comes in before, does his build fail :unamused:.

For this we must wait mostly 24 hours before there ready.

Looking currently to find a way to prevent this, see "addon-system-external" on Slack.

**Pull request merged**
