### PR TITLE
Enable seeking while paused 

### PR DESCRIPTION
**Pull request by emveepee**
Kodi reads live TV stream while paused, need to keep stream open to allow seeking and avoid crash

### CODE REVIEW

**Comment by phunkyfish** [comment]
This one is just missing the addon xml and changelog

**Comment by emveepee** [comment]
> 
> 
> This one is just missing the addon xml and changelog

Are you suggesting that we need a changelog and version for every PR? @AlwinEsch created 4.3.1 without a changelog and I was piggy backing off that "version" for when we tag   I have another change planned I was going to update the changelog at that time.

**Comment by emveepee** [comment]
Oops clicked close and comment in error.

**Comment by phunkyfish** [comment]
I guess once the changelog is updated per release that’s fine.

@AlwinEsch maintains all binary addons so generally we regard him as having superpowers 😃

**Review by phunkyfish — APPROVED** [review]
LGTM

**Pull request merged**
