### PR TITLE
Added support for Jarvis timers

### PR DESCRIPTION
**Pull request by sub3**
Added initial support for Jarvis style timers, recurring recordings etc.

### CODE REVIEW

**Comment by ksooo** [comment]
Yeah. Many thanks. Will take a closer look at the code tomorrow, if you like. Cannot runtime test, though. Don't have NextPVR at hand...

**Comment by ksooo** [comment]
Cannot say much about nextpvr specific code. All my other comments are mostly just nitpicking...

**Comment by sub3** [comment]
Ok, I've done updates that should address these items.

**Comment by ksooo** [comment]
Thanks for fixing all the things I have requested. From my perspective good to go now (though not runtime-tested). @Jalle19 your thoughts on this?

**Comment by sub3** [comment]
Any thoughts on when this will be merged?

**Comment by ksooo** [comment]
@Jalle19 ping

**Comment by Jalle19** [comment]
Can't really make an intelligent comment on the code since I've never looked at it before. No objections for me as long as people say it works.

**Comment by ksooo** [comment]
>  No objections for me as long as people say it works.

@sub3 as far as I remember you asked people in the forum for feedback, right? So, what do they say? Does it work?

**Comment by sub3** [comment]
I've not had a lot of feedback, but the couple of people have tried it said it worked fine for them. It also tested fine for me. 

After this version is merged, I'll start a second round of changes to the addon, to add keyword support.

**Comment by ksooo** [comment]
@sub3 okay. Here we go...

**Comment by sub3** [comment]
Thanks

**Comment by ksooo** [comment]
You're welcome and thanks again for your contribution. :-)

**Pull request merged**
