### PR TITLE
Style edit and performance change

### PR DESCRIPTION
**Pull request by emveepee**
New .cpp files were crlf, changed to lf.   Change GetNumChannels() to use variables.  Kodi polls GetNumChannels() constantly when the Recordings menu is open.

### CODE REVIEW

**Comment by phunkyfish** [comment]
Could you split the functional change and the refactoring into separate commits? There is no way to see what you have changed.

It's a good rule of thumb for any future work.

**Comment by emveepee** [comment]
> Could you split the functional change and the refactoring into separate commits? There is no way to see what you have changed.
> 
> It's a good rule of thumb for any future work.

Ok hope this is easier.  I used dos2unix first then applied changes.   Not sure why Kodi  so aggressive in Recordings with CPVRClients::GetBackendProperties() polling so often.  I already don't bother getting drive space because of this.

**Review by phunkyfish — APPROVED** [review]
Nice

**Comment by emveepee** [comment]
@sub3  when you have a chance could you merge this please.  I don't want to wait to bring the pause change and would like to get started with the changes for PR 16485

**Pull request merged**
