### PR TITLE
Updated to PVR Addon API 4.2.0 

### PR DESCRIPTION
**Pull request by gfisher2**
Updated to PVR Addon API 4.2.0

### CODE REVIEW

**Comment by ksooo** [comment]
Please update https://github.com/kodi-pvr/pvr.nextpvr/blob/master/pvr.nextpvr/changelog.txt

**Comment by MartijnKaijser** [comment]
Also squash all changes in single commit to get the "merge commits" away

**Comment by gfisher2** [comment]
changelog.txt updated, squashed now into one commit.    thx

**Comment by ksooo** [comment]
Could you please change the commit message to something more meaningful, like "Updated to PVR Addon API 4.2.0"? Thx.

**Comment by ksooo** [comment]
My suggestion for changelog it to phrase this like "always":
<pre>
v2.0.3
 - Updated to PVR API v4.2.0
</pre>
That's enough. See prvious changleog entries for API bumps.

BTW: Adding IsRealTimeStream function is actually not a fix. This IS the implementation of API 4.2.0. ;-)

**Comment by gfisher2** [comment]
Thanks.  Done.  For completeness- this update addresses:  "ERROR: Unable to load /usr/lib/kodi/addons/pvr.nextpvr/pvr.nextpvr.so, reason: /usr/lib/kodi/addons/pvr.nextpvr/pvr.nextpvr.so: undefined symbol: IsRealTimeStream"

**Comment by ksooo** [comment]
Thanks for your contribution.

**Comment by gfisher2** [comment]
Thank you.

**Pull request merged**
